=== karimibrahimmustafa/projects/DBMS/dataBase1/table1.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT table1 (row)+>

<!ATTLIST table1 xmlns CDATA #FIXED ''Data NMTOKEN #REQUIRED>
<!ELEMENT row (column1,column2)>

<!ATTLIST row xmlns CDATA #FIXED ''>
<!ELEMENT column1 (#PCDATA)>

<!ATTLIST column1 xmlns CDATA #FIXED '' Type NMTOKEN #REQUIRED>
<!ELEMENT column2 (#PCDATA)>

<!ATTLIST column2 xmlns CDATA #FIXED '' Type NMTOKEN #REQUIRED>

=== karimibrahimmustafa/projects/DBMS/dataBase1/table1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE table1 PUBLIC "" "table1.dtd">
<table1 Data="True">
<row>
<column1 Type="int">20</column1>
<column2 Type="varchar">mahmoud</column2>
</row>
<row>
<column1 Type="int">20</column1>
<column2 Type="varchar">mahmoud</column2>
</row>
<row>
<column1 Type="int">30</column1>
<column2 Type="varchar">mohamed</column2>
</row>
<row>
<column1 Type="int">30</column1>
<column2 Type="varchar">mohamed</column2>
</row>
<row>
<column1 Type="int">400</column1>
<column2 Type="varchar">koko</column2>
</row>
<row>
<column1 Type="int">400</column1>
<column2 Type="varchar">koko</column2>
</row>
<row>
<column1 Type="int">240</column1>
<column2 Type="varchar">elsawy</column2>
</row>
<row>
<column1 Type="int">240</column1>
<column2 Type="varchar">elsawy</column2>
</row>
</table1>
