=== karimibrahimmustafa/projects/DBMS/computer/components.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT components (row)+>

<!ATTLIST components xmlns CDATA #FIXED ''Data NMTOKEN #REQUIRED>
<!ELEMENT row (number,types)>

<!ATTLIST row xmlns CDATA #FIXED ''>
<!ELEMENT number (#PCDATA)>

<!ATTLIST number xmlns CDATA #FIXED '' Type NMTOKEN #REQUIRED>
<!ELEMENT types (#PCDATA)>

<!ATTLIST types xmlns CDATA #FIXED '' Type NMTOKEN #REQUIRED>

=== karimibrahimmustafa/projects/DBMS/computer/components.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE components PUBLIC "" "components.dtd">
<components Data="True">
<row>
<number Type="int">23</number>
<types Type="varchar">apple</types>
</row>
<row>
<number Type="int">23</number>
<types Type="varchar">apple</types>
</row>
<row>
<number Type="int">43</number>
<types Type="varchar">hp</types>
</row>
<row>
<number Type="int">43</number>
<types Type="varchar">hp</types>
</row>
<row>
<number Type="int">353</number>
<types Type="varchar">intel</types>
</row>
<row>
<number Type="int">353</number>
<types Type="varchar">intel</types>
</row>
</components>
