=== karimibrahimmustafa/projects/DBMS/kimo5/student2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT student2 (row)+>

<!ATTLIST student2 xmlns CDATA #FIXED ''Data NMTOKEN #REQUIRED>
<!ELEMENT row (english,engineering,physics,chemistry)>

<!ATTLIST row xmlns CDATA #FIXED ''>
<!ELEMENT english (#PCDATA)>

<!ATTLIST english xmlns CDATA #FIXED 'varchar' Type NMTOKEN #REQUIRED>
<!ELEMENT engineering (#PCDATA)>

<!ATTLIST engineering xmlns CDATA #FIXED 'varchar' Type NMTOKEN #REQUIRED>
<!ELEMENT physics (#PCDATA)>

<!ATTLIST physics xmlns CDATA #FIXED 'varchar' Type NMTOKEN #REQUIRED>
<!ELEMENT chemistry (#PCDATA)>

<!ATTLIST chemistry xmlns CDATA #FIXED 'intr' Type NMTOKEN #REQUIRED>

=== karimibrahimmustafa/projects/DBMS/kimo5/student2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE student2 PUBLIC "" "student2.dtd">
<student2 Data="True">
<row>
<english Type="varchar">2</english>
<engineering Type="varchar">10</engineering>
<physics Type="varchar">12</physics>
<chemistry Type="intr">20</chemistry>
</row>
<row>
<english Type="varchar">15</english>
<engineering Type="varchar">21</engineering>
<physics Type="varchar">55</physics>
<chemistry Type="intr">6</chemistry>
</row>
<row>
<english Type="varchar">1000</english>
<engineering Type="varchar">151515</engineering>
<physics Type="varchar">123</physics>
<chemistry Type="intr">154</chemistry>
</row>
<row>
<english Type="varchar">kimo</english>
<engineering Type="varchar">hi</engineering>
<physics Type="varchar">huhu</physics>
<chemistry Type="intr">6666</chemistry>
</row>
<row>
<english Type="varchar">10065650</english>
<engineering Type="varchar">15165655515</engineering>
<physics Type="varchar">16523</physics>
<chemistry Type="intr">1545544</chemistry>
</row>
</student2>
